---
title: "Rebeccas project"
author: "Mohan Bi"
date: "2024-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
####################
# Data preparation #
####################

```{r data prepare}
df_meta = read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/meta_data.csv")[-1]
df_21 = read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/plant_2021.csv")
df_22 = read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/plant_2022.csv")
df_23 = read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/plant_2023.csv")
df_24 = read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/plant_2024.csv")
plants_category = read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/plant_category.csv")[-1]
plant_family <- unique(plants_category$family)
plant_species <- unique(plants_category$Species)
plant_genus <- unique(plants_category$genus)
colnames(df_21)[1] <- "SampleNo"
colnames(df_22)[1] <- "SampleNo"
colnames(df_23)[1] <- "SampleNo"
colnames(df_24)[1] <- "SampleNo"

grass <- plants_category[which(plants_category["functional_group"]=="grass"),1]
herb <- plants_category[which(plants_category["functional_group"]=="herb"),1]
legume <- plants_category[which(plants_category["functional_group"]=="legume"),1]


df_21_sum <- df_21%>%
  mutate(grass_sum = apply(df_21[,grass], MARGIN = 1, sum))%>%
  mutate(herb_sum = apply(df_21[,herb], MARGIN = 1, sum))%>%
  mutate(legume_sum = apply(df_21[,legume], MARGIN = 1, sum))%>%
  mutate(all_abundance = grass_sum+herb_sum+legume_sum)%>%
  mutate(grass_prop = grass_sum/all_abundance)%>%
  mutate(herb_prop = herb_sum/all_abundance)%>%
  mutate(legume_prop = legume_sum/all_abundance)%>%
  mutate(time = rep(0,154))%>%
  left_join(df_meta)

df_22_sum <- df_22%>%
  mutate(grass_sum = apply(df_22[,grass], MARGIN = 1, sum))%>%
  mutate(herb_sum = apply(df_22[,herb], MARGIN = 1, sum))%>%
  mutate(legume_sum = apply(df_22[,legume], MARGIN = 1, sum))%>%
  mutate(all_abundance = grass_sum+herb_sum+legume_sum)%>%
  mutate(grass_prop = grass_sum/all_abundance)%>%
  mutate(herb_prop = herb_sum/all_abundance)%>%
  mutate(legume_prop = legume_sum/all_abundance)%>%
  mutate(time = rep(1,154))%>%
  left_join(df_meta)
  
df_23_sum <- df_23%>%
  mutate(grass_sum = apply(df_23[,grass], MARGIN = 1, sum))%>%
  mutate(herb_sum = apply(df_23[,herb], MARGIN = 1, sum))%>%
  mutate(legume_sum = apply(df_23[,legume], MARGIN = 1, sum))%>%
  mutate(all_abundance = grass_sum+herb_sum+legume_sum)%>%
  mutate(grass_prop = grass_sum/all_abundance)%>%
  mutate(herb_prop = herb_sum/all_abundance)%>%
  mutate(legume_prop = legume_sum/all_abundance)%>%
  mutate(time = rep(2,154))%>%
  left_join(df_meta)

df_24_sum <- df_24%>%
  mutate(grass_sum = apply(df_24[,grass], MARGIN = 1, sum))%>%
  mutate(herb_sum = apply(df_24[,herb], MARGIN = 1, sum))%>%
  mutate(legume_sum = apply(df_24[,legume], MARGIN = 1, sum))%>%
  mutate(all_abundance = grass_sum+herb_sum+legume_sum)%>%
  mutate(grass_prop = grass_sum/all_abundance)%>%
  mutate(herb_prop = herb_sum/all_abundance)%>%
  mutate(legume_prop = legume_sum/all_abundance)%>%
  mutate(time = rep(3,154))%>%
  left_join(df_meta)

longitudinal_data <- rbind(df_21_sum,df_22_sum,df_23_sum,df_24_sum)

#Functions for calculating plant richness and simpson diversity
Richness <- function(object){
  richness <- 0
  for (i in 1:length(object)) {
    if(object[i]>0) richness <- richness + 1
  }
  return(richness)
}

Simpson_diversity <- function(object){
  Diver <- 0
  N <- sum(object)
  for (i in 1:length(object)) {
    D <- (object[i]/N)^2
    Diver <- Diver+D
  }
  output <- 1-Diver
  return(output)
}

longitudinal_data$richness_all <- rep(0,nrow(longitudinal_data))
longitudinal_data$diversity_all <- rep(0,nrow(longitudinal_data))
longitudinal_data$diversity_grass <- rep(0,nrow(longitudinal_data))
longitudinal_data$diversity_herb <- rep(0,nrow(longitudinal_data))
longitudinal_data$diversity_legume <- rep(0,nrow(longitudinal_data))

#calculate diversity within each functional group.

for (i in 1:nrow(longitudinal_data)) {
  
  species <- longitudinal_data[i,plant_species]
  grass_num <- longitudinal_data[i,grass]
  herb_num <- longitudinal_data[i,herb]
  legume_num <- longitudinal_data[i,legume]
  
  longitudinal_data[i,"richness_all"] <- Richness(species)
  longitudinal_data[i,"diversity_all"] <- Simpson_diversity(species)
  longitudinal_data[i,"diversity_grass"] <- Simpson_diversity(grass_num)
  longitudinal_data[i,"diversity_herb"] <- Simpson_diversity(herb_num)
  longitudinal_data[i,"diversity_legume"] <- Simpson_diversity(legume_num)
}
longitudinal_data[longitudinal_data=="2F"] <-"2"
longitudinal_data[longitudinal_data=="4F"] <-"4"
longitudinal_data[longitudinal_data=="6F"] <-"6"
longitudinal_data[longitudinal_data=="8F"] <-"8"
longitudinal_data[longitudinal_data=="10F"] <-"10"
#write.csv(longitudinal_data, "/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/longitudinal_data.csv")
```

###############################################
# Plant community composition (Ternary plots) 
###############################################

```{r ternary plots}
library(dplyr) # for data manipulation
library(ggplot2) # for graphing
library(lme4) # for multilevel models
library(lmerTest) # for p-values
library(performance) # for ICC

df = read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/longitudinal_data.csv")
df[is.na(df)]<-0

#Ternary plots for three plant_functional groups

library(Ternary)

df <- df%>%
  select(59:83)

df_1 <- df[df["time"]==3,] #Choosing the data set from which year ("0" = 2021; "1" = 2022, "2" = 2023, "3" = 2024)


# Define a colour spectrum
spectrumBins <- 7 # Number of bins to use
mySpectrum <- rowCol <- hcl.colors(spectrumBins, palette = "viridis")

mySpectrum <- c( "#82828290","#FDE33380","#7ED35790","#7ED35790","#00B28A90","#00B28A90","#00829890","#00829890","#27498390","#27498390","#4B005590")

# Cut our reflectance data into categories
binnedReflectance <- cut(df_1$Lv, 11)

# Assign each data point a colour from the spectrum
pointCol <- mySpectrum[binnedReflectance]

# Initialize the plot
TernaryPlot(atip = expression(Grass),
            btip = expression(Herb),
            ctip = expression(Legume)
)

# Plot the points
TernaryPoints(df_1[, c("grass_sum", "herb_sum", "legume_sum")],
              cex = 1.5, # Point size
              col = pointCol,  # Point colour
              pch = 16         # Plotting symbol (16 = filled circle)
)

# Legend for colour scale
PlotTools::SpectrumLegend(
  "topleft",
  cex = 0.8, # Font size
  palette = mySpectrum,
  legend = paste(
    seq(from = max(df_1$Lv), to = min(df_1$Lv),
        length.out = 5)
  ),
  bty = "n", # No framing box
  xpd = NA, # Don't clip at margins
  # title.font = 2, # Bold.  Argument only available in R>3.6
  title = "Number of factors"
)
```
###############################################
# Plant community composition (NMDS analysis) 
###############################################
In this section we analysis the plant community composition shift between different treatment groups in different years.
```{r message=FALSE, include=FALSE}
library(vegan)

df <- read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/longitudinal_data.csv")[-1]
plant_community <- colnames(df)[2:57]
community_y0 <- df[df[,"time"]==3, c("SampleNo","Lv",plant_community)] #Choosing the data set from which year ("0" = 2021; "1" = 2022, "2" = 2023, "3" = 2024)
#community_y1 <- df[df[,"time"]==1,plant_community]
#community_y2 <- df[df[,"time"]==2,plant_community]
#community_y3 <- df[df[,"time"]==3,plant_community]

#Converting absolute abundance to relative abundance
community_y0_relativ <- decostand(community_y0[,c(3:58)], "total")
community_groups <-community_y0[,c(1:2)]

#Calculating distance matrix

community_y0_Matrix <- as.matrix(community_y0_relativ, labels =T)

#NMDS analysis using metaMDS
community_y0_NMDS <- metaMDS(community_y0_Matrix,
                             distance = "bray",
                             k = 2,
                             maxit =999,
                             trymax = 500,
                             wascores = TRUE)

stressplot(community_y0_NMDS )
```

```{r NMDS plots}
#assign color to treatments
treatments <- as.vector(community_groups$Lv)
colvec <- c("#726658","#FDE333","#7ED357","#00B28A","#008298","#274983","#4B0055")
level<-c("0","1","2","4","6","8","10")
col_code <- c()
for (i in 1:length(treatments)) {
  col_code[i] <- colvec[which(level==treatments[i])]
}

#ploting
plot(community_y0_NMDS, type="n", display = "sites")
with(community_groups, points(community_y0_NMDS, display = "sites", col = col_code,pch = rep(16,7),))
ordispider(community_y0_NMDS, groups = treatments, col= colvec, label=F)
#Calculating and plotting centroids 
scrs <- scores(community_y0_NMDS, display = "sites", "species")
cent <- aggregate(scrs ~ Lv, data = community_groups, FUN = "mean")
#names(cent)[-1]<-colnames(scrs)
points(cent[,-1],
       pch = rep(15,7),
       col = colvec,
       lwd = 3.0,
       cex = 2.0)

#write.csv(scrs,"/Users/mohanbi/Documents/GitHub/Rebeccas project/Modeling/NMDS_1.csv")
```

#################
# Main analysis #
#################
```{r Library, message=FALSE, include=FALSE}
library(ggplot2)
library(ggridges)
library(ggepi)
library(patchwork)
library(party)
library(caret)
library(dplyr)
library(randomForest)
library(dabestr)
library(openxlsx)
library(dabestr)
```

```{r split working dataset}
df_all_4y <- read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/longitudinal_data.csv")[-1]
df_flower_y1 <- read.csv("/Users/mohanbi/Documents/GitHub/Rebeccas project/Final harvest/flower_data.csv")[-1]
df_y0 <- df_all_4y[df_all_4y[,"time"]=="0",] #2021 (pretreatment)
df_y1 <- df_all_4y[df_all_4y[,"time"]=="1",] #2022
df_y2 <- df_all_4y[df_all_4y[,"time"]=="2",] #2023
df_y3 <- df_all_4y[df_all_4y[,"time"]=="3",] #2024
```

```{r transform data}
df_tmp <- df_y1
#df_tmp <- df_y2
#df_tmp <- df_y3
#df_tmp <- df_flower_y1

data_transform <- function(dataset){
  lv_1 <- dataset[dataset[,"Lv"]==1,]
  lv_1 <- lv_1 %>% mutate(remark = rep(1,80))
  DataFrame <- rbind(dataset, lv_1)
  return(DataFrame)
}

df <- data_transform(df_tmp)
```

```{r plant cover}
responses <-c("grass_sum","herb_sum","legume_sum","richness_all")
#responses <-c("legume_sum")
#responses <-c("grass_prop","herb_prop","legume_prop","richness_all")
#responses <-c("richness_all","diversity_all","diversity_grass","diversity_herb","diversity_legume")
stressors = c("W","N","D","HM","MP","S","A","I","AF","SF")
levels = c("1", "2", "4", "6", "8","10")
#responses <- c("richness_all","Trifolium_pratense","Cichorium_intybus","Festuca_arundinacea")5responses <- c("Trifolium_pratense","Trifolium_repens","Plantago_lanceolata","Cichorium_intybus","Lolium_perenne","Lolium_multiflorum_agg.","Festuca_arundinacea","Phleum_pratense","Dactylis_glomerata") #sown plants
df <- df %>%
  arrange(factor(.$remark, levels = c("CT","W","N","D","HM","MP","S","A","I","AF","SF","1", "2", "4", "6", "8","10")))
treatment <- unique(df$remark)
n_iter = 1000
df$remark=factor(df$remark, levels = unique(df$remark))
```

```{r flowers}
responses <- c("pollinator_vis_22", "flowers_Tp_DOY151_22", "mean_infected_leaf_Tp_mar22")
stressors = c("W","N","D","HM","MP","S","A","I","AF","SF")
levels = c("1", "2", "4", "6", "8","10")
df <- df %>%
  arrange(factor(.$remark, levels = c("CT","W","N","D","HM","MP","S","A","I","AF","SF","1", "2", "4", "6", "8","10")))
treatment <- unique(df$remark)
n_iter = 1000
df$remark=factor(df$remark, levels = unique(df$remark))
```

```{r main analysis}

response_mean_all = list()
response_ES_all   = list()
joint_ES_null_all = list()
ES_for_each_all   = list()
g_rawdata_all     = list()
g_ms_all          = list()
p_ES_all          = list()

for (i_response in responses) {
  #bootstrap mean
  response_mean = BootStrap_mean(i_response)
  response_mean_all[[i_response]] = response_mean
  #effect size
  response_ES_bs  = BootStrap_ES_rep(i_response)
  response_ES     = BootStrap_ES_summary(response_ES_bs)
  response_ES_all[[i_response]]   = response_ES
  #Null model
  Null_ES_bs0     = Null_distribution_rep(i_response)
  Null_ES_bs      = Null_distribution_rep_transform(Null_ES_bs0)
  
  joint_ES_null   = NHST_summary(Null_ES_bs, response_ES_bs)
  joint_ES_null_all[[i_response]] = bind_rows(joint_ES_null, .id = "column_label")
  
  ES_plot         = NHST_summary_transform(joint_ES_null)
  ES_for_each     = Expected_ES_for_each(Null_ES_bs0)
  ES_for_each_all[[i_response]]   = ES_for_each
  
  #Plot_ES
  p_ES_all[[i_response]] =  local({
   i_response = i_response
   response_mean = response_mean

Mycolor_TR = c("#6D6E71A0","#72665850","#72665850","#72665850","#72665850","#72665850","#72665850","#72665850","#72665850","#72665850","#72665850","#FDE33350","#7ED35750","#00B28A50","#00829850","#27498350","#4B005550","#645B6C50")
Mycolor = c("#6D6E71","#726658","#726658","#726658","#726658","#726658","#726658","#726658","#726658","#726658","#726658","#645B6C","#645B6C","#645B6C","#645B6C","#645B6C","#645B6C")
   ggplot() +
     theme_bw()+
     theme(legend.position = 'none', axis.title.x=element_blank())+
     xlab(i_response) +
     coord_flip() +
     stat_density_ridges(data=df, aes_string(x = i_response, y = "remark", fill = "remark"),
                         geom = "density_ridges_gradient",
                         rel_min_height = 0.01,
                         jittered_points = TRUE, color = "#00000000",
                         position = position_points_jitter(height = .2, yoffset = .15),
                         point_size = 1, point_alpha = .3,
                         scale = .5) +
     scale_fill_manual(values  = Mycolor_TR)+
     geom_estci(data = response_mean, aes(x = mean, y = target, xmin=X2.5., xmax=X97.5.,
                                                      xintercept= response_mean[1,"mean"], color = target), center.linecolour = "black", size=0.6, ci.linesize = 0.5, position=position_nudge(y = -0.15))+
     scale_color_manual(values = Mycolor)+
     theme(panel.background = element_rect(fill = "#4D728510", color = "white"),
            panel.grid.major = element_line(color = "white", size = 0.1),
            panel.grid.minor = element_line(color = "white", size = 0.5))

  })
  
   #Plot Null model
  g_ms_all[[i_response]] = local({
  i_response = i_response
  ct_value = response_mean[1,"mean"]
  ES_plot = ES_plot
  
  for(i in 1:4) ES_plot[[i]][,2:4] = ES_plot[[i]][,2:4] + ct_value

  ggplot()+
    theme_bw()+
    theme(legend.position = 'none', axis.title.x=element_blank(), axis.title.y=element_blank())+
    theme(legend.position = "none")  +
    coord_flip() +
    scale_y_discrete(limits = factor(c("2","4","6","8","10"), levels=c("2","4","6","8","10"))) +
    
    ### Mean & CI ###
    # 3 assumptions
      geom_estci(data=ES_plot[["Additive"]], aes(x = Mean, y = Lv, xmin=Low, xmax=High, xintercept=ct_value), 
                 color="#008900AA", size=0.4, ci.linesize = 0.4, position=position_nudge(y = +0.1)) +
      geom_estci(data=ES_plot[["Multiplicative"]], aes(x = Mean, y = Lv, xmin=Low, xmax=High, xintercept=ct_value), 
                 color="#ff0083AA", size=0.4, ci.linesize = 0.4, position=position_nudge(y = +0.2)) +
      geom_estci(data=ES_plot[["Dominative"]], aes(x = Mean, y = Lv, xmin=Low, xmax=High, xintercept=ct_value), 
                 color="#0000A0AA", size=0.4, ci.linesize = 0.4, position=position_nudge(y = +0.3)) +
      
    # Actual ES
      geom_estci(data=ES_plot[["Actual"]], aes(x = Mean, y = Lv, xmin=Low, xmax=High, xintercept=ct_value), 
                                    size=0.6, ci.linesize = 0.6, position=position_nudge(y = 0))
  })
}

```

```{r radar plots}
library(tidyverse)
library(viridis)
library(patchwork)
library(hrbrthemes)
library(fmsb)
library(colormap)

v_treat_2021 <- numeric(0)
treat_2021 <-c()
v_treat_2022 <- numeric(0)
treat_2022 <-c()
v_treat_2023 <- numeric(0)
treat_2023 <-c()
v_treat_2024 <- numeric(0)
treat_2024 <-c()

for (i_response in responses) {
  v_treat_2021 <- response_mean_all_2021[[i_response]][17,3]
  treat_2021 <- append(treat_2021,v_treat_2021)
  v_treat_2022 <- response_mean_all_2022[[i_response]][17,3]
  treat_2022 <- append(treat_2022,v_treat_2022)
  v_treat_2023 <- response_mean_all_2023[[i_response]][17,3]
  treat_2023 <- append(treat_2023,v_treat_2023)
  v_treat_2024 <- response_mean_all_2024[[i_response]][17,3]
  treat_2024 <- append(treat_2024,v_treat_2024)
}

data_plant <- as.data.frame(matrix(c(treat_2021,treat_2022,treat_2023,treat_2024), nrow = 4, ncol = length(responses), byrow = TRUE))
colnames(data_plant)<- c(responses)
data_plant <- rbind(rep(100,9),rep(0,9), data_plant)

# Prepare color

colors_border=c( "#66666695","#FDE33395", "#00A79095", "#48196495"  )
colors_in=c( "#66666630", "#FDE33330", "#00A79030", "#48196430")

# Custom the radarChart
radarchart( data_plant, axistype=1,
            
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=4, plty=1 ,
            
            #custom the grid
            cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,100,20), cglwd=1.1,
            
            #custom labels
            vlcex=0.8
)
# Legend
legend(x=0.85, y=1, legend = c("Control", "2022","2023","2024"), bty = "n", pch=20 , col=colors_border, text.col = "black", cex=0.9, pt.cex=1.6)

##############################################
#Figure 2

v_treat <- numeric(0)
treat <-c()
v_control <- numeric(0)
control <-c()

for (i_response in responses) {
  v_control <- response_mean_all_2024[[i_response]][1,3]
  control <- append(control,v_control)
  v_treat <- response_mean_all_2024[[i_response]][17,3]
  treat <- append(treat,v_treat)
}

data_plant <- as.data.frame(matrix(c(control,treat), nrow = 2, ncol = length(responses), byrow = TRUE))
colnames(data_plant)<- c(responses)
data_plant <- rbind(rep(100,9),rep(0,9), data_plant)


colors_border=c( "#66666695","#4B005595" )
colors_in=c( "#66666630", "#4B005530")

# Custom the radarChart
radarchart( data_plant, axistype=1,
            
            #custom polygon
            pcol=colors_border , pfcol=colors_in , plwd=4, plty=1 ,
            
            #custom the grid
            cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,100,25), cglwd=1.1,
            
            #custom labels
            vlcex=0.8
)
# Legend
legend(x=0.85, y=1, legend = c("Control", "treat"), bty = "n", pch=20 , col=colors_border, text.col = "black", cex=0.9, pt.cex=1.6)

#color_scale <- c("#726658","#FDE333","#7ED357","#00B28A","#008298","#274983","#4B0055")
```

```{r random forest}

df.rf = df[df[, "remark"] %in% levels,]

lv_list  = unique(df.rf[,"Lv"])
id_lv1   = which(df.rf[,"Lv"]==1)
id_lvh   = which(df.rf[,"Lv"]>1)

n_data   = nrow(df.rf)
n_lv1    = sum(df.rf[,"Lv"]==1)
n_lvh    = sum(df.rf[,"Lv"]!=1)
n_eachlv = 12 
n_tree   = 25
n_iter2  = 50

rf.r2 = data.frame(matrix(NA, ncol=3, nrow=4*n_iter2*length(responses)))
rf.r2[,1] = rep(responses,each=4*n_iter2)
rf.r2[,2] = rep(c("ES","Lv", "LvES", "All"), n_iter2*length(responses))
rf.r2[,2] = factor(rf.r2[,2], levels=c("ES","Lv", "LvES", "All"))
colnames(rf.r2) = c("Response", "Model", "R2")

rf.pred = data.frame(matrix(NA, ncol=7, nrow=n_iter2*length(responses)))
rf.pred[,1] = rep(responses,each=n_iter2)
colnames(rf.pred) = c("Response", lv_list)

rf.vimp = data.frame(matrix(NA, ncol=12, nrow=n_iter2*length(responses)))
rf.vimp[,1] = rep(responses,each=n_iter2) 
colnames(rf.vimp) = c("Response", stressors,"Lv")

rf.prediction.all = list()

j = 0
for(i_response in responses){
  
  df.rf.tmp = cbind(df.rf, ES_for_each_all[[i_response]])
  #define the formulas for three random forest models
  eval(parse(text=(paste("fml.ES   = formula(",i_response,"~E2)", sep=""))))
  eval(parse(text=(paste("fml.Lv   = formula(",i_response,"~Lv)", sep=""))))
  eval(parse(text=(paste("fml.LvES = formula(",i_response,"~", paste(c("Lv","E2"), collapse=" + "),")", sep=""))))
  eval(parse(text=(paste("fml      = formula(",i_response,"~", paste(c("Lv","E2", stressors), collapse=" + "),")", sep=""))))
  
  for(i in 1:n_iter2){
    j = j + 1
    # bootstrap resampling
    set.seed(j)
    # take 12 samples from Lv1, and take 12 samples from the other levels for balanced resampling
    rid = c(sample(id_lv1, n_eachlv, replace=T), sample(id_lvh, n_lvh, replace=T))
    rdf = df.rf.tmp[rid,]
    rf_model      = tryCatch({
      cforest(fml,      data = rdf, control=cforest_control(ntree=n_tree, minsplit = 5, minbucket=2))},
      error = function(e) {cforest(fml,   data = rdf, control=cforest_control(ntree=n_tree, minsplit = 5, minbucket=2))})
    rf_model.ES   = cforest(fml.ES,   data = rdf, control=cforest_control(ntree=n_tree, minsplit = 5, minbucket=2))
    rf_model.LvES = cforest(fml.LvES, data = rdf, control=cforest_control(ntree=n_tree, minsplit = 5, minbucket=2))
    rf_model.Lv   = cforest(fml.Lv,   data = rdf, control=cforest_control(ntree=n_tree, minsplit = 5, minbucket=2))  
    # shuffling corresponding variables for evaluating R2 reduction
    # rdf.test.LvID = rdf
    # rdf.test.LvID[,colnames(ES_for_each_all[[i_response]])] = apply(rdf.test.LvID[,colnames(ES_for_each_all[[i_response]])],2,sample)  
    
    # evaluating fitting performance
    rf_prdct.ES   = tryCatch({predict(rf_model.ES, OOB=T)}, error=function(e){rep(0,length(rid))})
    rf_prdct.Lv   = tryCatch({predict(rf_model.Lv, OOB=T)}, error=function(e){rep(0,length(rid))})
    rf_prdct.LvES = tryCatch({predict(rf_model.LvES, OOB=T)}, error=function(e){rep(0,length(rid))})
    rf_prdct.All  = tryCatch({predict(rf_model, OOB=T)}, error=function(e){rep(0,length(rid))})
    
    rf.r2[4*j-3,3]    = postResample(rf_prdct.ES,rdf[,i_response])[2]
    rf.r2[4*j-2,3]    = postResample(rf_prdct.Lv,rdf[,i_response])[2]
    rf.r2[4*j-1,3]    = postResample(rf_prdct.LvES,rdf[,i_response])[2]
    rf.r2[4*j-0,3]    = postResample(rf_prdct.All,rdf[,i_response])[2]
    
    # variable importance
    set.seed(j)
    tmp.vimp = numeric(0)
    for(itmp in 1:5) tmp.vimp = rbind(tmp.vimp,varimp(rf_model))
    tmp.vimp = apply(tmp.vimp,2,mean)
    tmp.vimp = tmp.vimp/sum(tmp.vimp)
    rf.vimp[j, 2:(length(tmp.vimp)+1)] = tmp.vimp*rf.r2[2*j-0,3]*100
    
    # fitting curve
    tmp.curve = c()
    for(i_lv in lv_list){
      tmp.curve = append(tmp.curve, mean(rf_prdct.All[rdf[,"Lv"]==i_lv]))
    }
    rf.pred[j,2:7]    =  tmp.curve
  }
  
  rf_model      = cforest(fml,      data = df.rf.tmp, control=cforest_control(ntree=n_tree, minsplit = 5, minbucket=2))
  rf_model.Lv      = cforest(fml.Lv,      data = df.rf.tmp, control=cforest_control(ntree=n_tree, minsplit = 5, minbucket=2))
  rf_model.ES   = cforest(fml.ES,   data = df.rf.tmp, control=cforest_control(ntree=n_tree, minsplit = 5, minbucket=2))
  rf_model.LvES = cforest(fml.LvES, data = df.rf.tmp, control=cforest_control(ntree=n_tree, minsplit = 5, minbucket=2))
  
  rf.prediction.all[[i_response]] = data.frame(
    Model     = rep(c("ES","Lv", "LvES", "All"), each = nrow(df.rf.tmp)),
    Predicted = c(predict(rf_model.ES, OOB=F),predict(rf_model.Lv, OOB=F), predict(rf_model.LvES, OOB=F), predict(rf_model, OOB=F)),
    Observed  = rep(df.rf.tmp[,i_response], 4))
  
}

rf.r2.summary = data.frame(matrix(NA,ncol=5,nrow=4*length(responses)))
colnames(rf.r2.summary) = c("Response","Model", "CI.low", "Mean", "CI.high")
rf.r2.summary[,1] = rep(responses,each=4)
rf.r2.summary[,2] = rep(c("ES","Lv", "LvES", "All"),length(responses))
rf.r2.summary[,2] = factor(rf.r2.summary[,2],levels=c("ES","Lv", "LvES", "All"))


rf.pred.summary = data.frame(matrix(NA,ncol=5,nrow=6*length(responses)))#changed 5 to 4*length(responses)
colnames(rf.pred.summary) = c("Response","Lv","CI.low", "Mean", "CI.high")
rf.pred.summary[,1] = rep(responses,each=length(lv_list))
rf.pred.summary[,2] = rep(lv_list, length(responses))

rf.vimp.summary = data.frame(matrix(NA,ncol=5,nrow=11*length(responses))) #Change variable number
colnames(rf.vimp.summary) = c("Response","Variable","CI.low", "Mean", "CI.high")
rf.vimp.summary[,1] = rep(responses,each=11)                              #Change variable number
rf.vimp.summary[,2] = rep(colnames(rf.vimp)[2:12], length(responses))  #Change variable column number
rf.vimp.summary[,2] = factor(rf.vimp.summary[,2], levels = unique(rf.vimp.summary[,2]))

j  = 0
for(i_response in responses){
  jj = 0
  jjj = 0
  rf.r2.summary[4*j+1,3:5] = quantile(rf.r2[which(rf.r2[,1]==i_response&rf.r2[,2]=="ES"),   3],c(.025,.50,.975), na.rm=T)
  rf.r2.summary[4*j+2,3:5] = quantile(rf.r2[which(rf.r2[,1]==i_response&rf.r2[,2]=="Lv"),   3],c(.025,.50,.975), na.rm=T)
  rf.r2.summary[4*j+3,3:5] = quantile(rf.r2[which(rf.r2[,1]==i_response&rf.r2[,2]=="LvES"), 3],c(.025,.50,.975), na.rm=T)
  rf.r2.summary[4*j+4,3:5] = quantile(rf.r2[which(rf.r2[,1]==i_response&rf.r2[,2]=="All"),  3],c(.025,.50,.975), na.rm=T)
  
  for(i_lv in lv_list){
    jj = jj + 1
    rf.pred.summary[6*j+jj,3:5]     = quantile(rf.pred[which(rf.pred[,1]==i_response),as.character(i_lv)],c(.025,.50,.975), na.rm=T)
  }#change 5-4*j+jj,3:5]
  
  for(i_var in colnames(rf.vimp)[2:12]){
    jjj = jjj + 1
    rf.vimp.summary[11*j+jjj,3:5]     = quantile(rf.vimp[which(rf.vimp[,1]==i_response),as.character(i_var)],c(.025,.50,.975), na.rm=T)
  }
  
  j = j + 1
  
}


#write.csv(rf.r2.summary, "/Users/mohanbi/Documents/GitHub/Rebeccas project/New_modeling/r2_flowers.csv")
#write.csv(rf.r2.summary, "C:/FSE/Random forest/Mydata/randomforest_pred_summary.csv")
#write.csv(rf.vimp.summary, "C:/FSE/Random forest/Mydata/randomforest_vimp_summary.csv")
```

```{r rf_plot}
g_rf_all     = list()
g_vimp_all   = list()
g_r2_all     = list()
g_correl_all = list()

for(i_response in responses){
  
  g_vimp_all[[i_response]] = local({
    i = i
    ggplot(data=rf.vimp.summary[rf.vimp.summary[,1]==i_response,],aes(x=factor(Variable, level = c("Warming","N_Addition","Drought","H_Metal","Microplastic","Salinity","Antibiotics","Insecticide","Antifungal_Agent","Surfactant","Lv")), y=Mean))+
      geom_bar(stat="identity", fill="#999999", alpha=0.5) +
      xlab("Variability explained [%]")+
      geom_errorbar(aes(ymax=CI.high, ymin=CI.low), width=.2, position=position_dodge(width=0.0)) +
      theme_bw()+
      theme(legend.position = 'none', axis.title.x=element_blank(),axis.title.y=element_blank())
  })
  
  g_r2_all[[i_response]] = local({
    i = i
    rf.r2 = rf.r2
    rf.r2.summary = rf.r2.summary 
    level_order=c("Lv","ES","LvES","All")
    ggplot(data=rf.r2[rf.r2[,1]==i_response,],aes(x=factor(Model,level = level_order),y=R2, fill=Model))+
      geom_violin( color="#00000000",alpha=.5,position=position_dodge(width=0.3),trim=F)+
      geom_pointrange(data=rf.r2.summary[rf.r2.summary[,1]==i_response,], aes(y=Mean, ymax=CI.high, ymin=CI.low,color=Model),fatten = 4, position=position_dodge(width=0.3)) +
      scale_fill_manual(values  = c("#E69F37","#E69F37","#8D2F1E","#9C9E83"))+ 
      scale_color_manual(values = c("#E69F37","#E69F37","#8D2F1E","#9C9E83"))+ 
      theme_bw() + ylim(c(0,1.0))+
      theme(axis.title.y=element_text(size=8))+
      ylab('Variability explained (R2%)')+
      theme(legend.position = 'none', axis.title.x=element_blank())+
      theme(panel.background = element_rect(fill = "#6D6E7130", color = "white"),
            panel.grid.major = element_line(color = "white", size = 0.2),
            panel.grid.minor = element_line(color = "white", size = 0.2))
  })
  
}
```

```{r combine plot}
p_ES_all[["Tp_cover_mar22"]]+g_ms_all[["Tp_cover_mar22"]]+g_r2_all[["Tp_cover_mar22"]]+
  p_ES_all[["Ci_cover_sep22"]]+g_ms_all[["Ci_cover_sep22"]]+g_r2_all[["Ci_cover_sep22"]]+
  p_ES_all[["Fa_cover_sep23"]]+g_ms_all[["Fa_cover_sep23"]]+g_r2_all[["Fa_cover_sep23"]]+
  p_ES_all[["richness_sep22"]]+g_ms_all[["richness_sep22"]]+g_r2_all[["richness_sep22"]]+
  plot_layout(ncol = 3, widths = c(5,2,2))

p_ES_all[["pollinator_vis_22"]]+g_ms_all[["pollinator_vis_22"]]+g_r2_all[["pollinator_vis_22"]]+
  p_ES_all[["flowers_Tp_DOY151_22"]]+g_ms_all[["flowers_Tp_DOY151_22"]]+g_r2_all[["flowers_Tp_DOY151_22"]]+
  p_ES_all[["total_vegetation_cover_sept22"]]+g_ms_all[["total_vegetation_cover_sept22"]]+g_r2_all[["total_vegetation_cover_sept22"]]+
  p_ES_all[["mean_infected_leaf_Tp_mar22"]]+g_ms_all[["mean_infected_leaf_Tp_mar22"]]+g_r2_all[["mean_infected_leaf_Tp_mar22"]]+
  p_ES_all[["Fa_cover_sep23.1"]]+g_ms_all[["Fa_cover_sep23.1"]]+g_r2_all[["Fa_cover_sep23.1"]]+
  plot_layout(ncol = 3, widths = c(5,2,2))

#write.csv(rf.r2.summary, "/Users/mohanbi/Documents/GitHub/Peter_urban_soil/randomforest_r2_summary.csv")
```

```{r factor interactions}
df<- na.roughfix(df) 
h_levels = levels[-1]
df_H=df[df[,"remark"]%in%h_levels,]
df_CK=df[df[,"remark"]=="CT",]
n_perm = 100

deviation_additive = data.frame(matrix(data = NA, nrow = nrow(df_H), ncol = 5))
colnames(deviation_additive)=c("Lv","deviation","P","actual_ES","null_ES")

deviation_multiplicative = data.frame(matrix(data = NA, nrow = nrow(df_H), ncol = 5))
colnames(deviation_multiplicative)=c("Lv","deviation","P","actual_ES","null_ES")

deviation_dominative = data.frame(matrix(data = NA, nrow = nrow(df_H), ncol = 5))
colnames(deviation_dominative)=c("Lv","deviation","P","actual_ES","null_ES")

deviation_3_models = list()

```

```{r factor interactions_loop}
for (i_response in responses) {
  
  for (treatment_i in 1:nrow(df_H)) {
    combination_i=c()
    combination_i=stressors[which(df_H[treatment_i,stressors]==1)]
    Null_modle_i_Treatment = NullModel( i_response, selected_factors = combination_i, n_perm = n_perm)
    Null_modle_summary_i_Treatment = NullModel_summary(Null_modle_i_Treatment, actual_data = df_H[treatment_i,i_response]) 
    
    deviation_additive[treatment_i,2]=(Null_modle_summary_i_Treatment[1,3]-Null_modle_summary_i_Treatment[2,3])/Null_modle_summary_i_Treatment[2,3]
    deviation_additive[treatment_i,3]=Null_modle_summary_i_Treatment[2,5]
    deviation_additive[treatment_i,"Lv"]=df_H[treatment_i,"Lv"]
    deviation_additive[treatment_i,4]=Null_modle_summary_i_Treatment[1,3]-mean(df_CK[,i_response])
    deviation_additive[treatment_i,5]=Null_modle_summary_i_Treatment[2,3]-mean(df_CK[,i_response])
    
    deviation_multiplicative[treatment_i,2]=(Null_modle_summary_i_Treatment[1,3]-Null_modle_summary_i_Treatment[3,3])/Null_modle_summary_i_Treatment[3,3]
    deviation_multiplicative[treatment_i,3]=Null_modle_summary_i_Treatment[3,5]
    deviation_multiplicative[treatment_i,1]=df_H[treatment_i,"Lv"]
    deviation_multiplicative[treatment_i,4]=Null_modle_summary_i_Treatment[1,3]-mean(df_CK[,i_response])
    deviation_multiplicative[treatment_i,5]=Null_modle_summary_i_Treatment[3,3]-mean(df_CK[,i_response])
    
    deviation_dominative[treatment_i,2]=(Null_modle_summary_i_Treatment[1,3]-Null_modle_summary_i_Treatment[4,3])/Null_modle_summary_i_Treatment[4,3]
    deviation_dominative[treatment_i,3]=Null_modle_summary_i_Treatment[4,5]
    deviation_dominative[treatment_i,1]=df_H[treatment_i,"Lv"]
    deviation_dominative[treatment_i,4]=Null_modle_summary_i_Treatment[1,3]-mean(df_CK[,i_response])
    deviation_dominative[treatment_i,5]=Null_modle_summary_i_Treatment[4,3]-mean(df_CK[,i_response])
  }
  
  deviation_3_models[[i_response]][["additive"]]=deviation_additive
  deviation_3_models[[i_response]][["multiplicative"]]=deviation_multiplicative
  deviation_3_models[[i_response]][["dominative"]]=deviation_dominative
  
}
```

```{r test}
positive_responses = c("Fa_cover_sep23","mean_infected_leaf_Tp_mar22","Fa_cover_sep23.1")
negativ_responses = c("Tp_cover_mar22", "Ci_cover_sep22","richness_sep22", "pollinator_vis_22","flowers_Tp_DOY151_22","total_vegetation_cover_sept22")

null_models = c("additive", "multiplicative", "dominative")

for (i_response in negativ_responses) {
  for (n_model in null_models) {
    for (i in 1:60) {
      if(deviation_3_models[[i_response]][[n_model]][["deviation"]][i]>0 ) deviation_3_models[[i_response]][[n_model]][["interaction_type"]][i] = "Antagonistic"
      if(deviation_3_models[[i_response]][[n_model]][["deviation"]][i]<0 ) deviation_3_models[[i_response]][[n_model]][["interaction_type"]][i] = "Synergistic"
      if(abs(deviation_3_models[[i_response]][[n_model]][["deviation"]][i])<0.0 ) deviation_3_models[[i_response]][[n_model]][i,"interaction_type"] = n_model ### threshold adjustment
      if(deviation_3_models[[i_response]][[n_model]][i,"P"]>=0.05) deviation_3_models[[i_response]][[n_model]][i,"interaction_type"] = n_model
    }
  }
}

for (i_response in positive_responses) {
  for (n_model in null_models) {
    for (i in 1:60) {
      if(deviation_3_models[[i_response]][[n_model]][["deviation"]][i]>0 ) deviation_3_models[[i_response]][[n_model]][["interaction_type"]][i] = "Synergistic"
      if(deviation_3_models[[i_response]][[n_model]][["deviation"]][i]<0 ) deviation_3_models[[i_response]][[n_model]][["interaction_type"]][i] = "Antagonistic"
      if(abs(deviation_3_models[[i_response]][[n_model]][["deviation"]][i])<0.0 ) deviation_3_models[[i_response]][[n_model]][i,"interaction_type"] = n_model ### threshold adjustment
      if(deviation_3_models[[i_response]][[n_model]][i,"P"]>=0.05) deviation_3_models[[i_response]][[n_model]][i,"interaction_type"] = n_model
    }
  }
}
```

```{r plot}
p_deviation = list()

for (i_response in responses) {
  p_deviation[[i_response]][["multiplicative"]] = 
    ggplot()+
    geom_point(data = deviation_3_models[[i_response]][["multiplicative"]], aes(x=Lv, y=deviation, color = interaction_type), size = 2)+
    xlab(i_response)+
    geom_boxplot(data = deviation_3_models[[i_response]][["multiplicative"]], aes( x=Lv, y=deviation, group = Lv), width = 1, fill = "#00000000", color = "#72665880")+
    scale_x_continuous(breaks = c(2,4,6,8,10))+
    scale_color_manual(values = c("Antagonistic"="#5499C780","multiplicative"="#90949780","Synergistic"="#F1666780"))+
    theme_bw()+
    theme(legend.position = 'none',axis.title.x = element_blank())+
    xlab(i_response)

}
```

```{r plot deviation}
p_ES_all[["grass_sum"]]+g_r2_all[["grass_sum"]]+p_deviation[["grass_sum"]]+
  p_ES_all[["herb_sum"]]+g_r2_all[["herb_sum"]]+p_deviation[["herb_sum"]]+
  p_ES_all[["legume_sum"]]+g_r2_all[["legume_sum"]]+p_deviation[["legume_sum"]]+
  p_ES_all[["richness_all"]]+g_r2_all[["richness_all"]]+p_deviation[["richness_all"]]+
  plot_layout(ncol = 3, widths = c(5,2,2))
```

```{r deviation significant test}
p_value_all <- list()

for (response_i in responses) {
  for (k in h_levels) {
    d_data <- deviation_3_models[[response_i]][["multiplicative"]]
    sig_test <- t.test(d_data[d_data[,"Lv"]==k,"deviation"])
    p_value <- sig_test$p.value
    p_value_all[[response_i]][[k]] <- p_value
  }
}

```

```{r RF significant test}
#library(reshape2)
r2_RF = rf.r2
Model = c("ES","LvES","All")
r2_test_all = list()

for (i_response in responses) {
  population_M1 = filter(r2_RF, Response == i_response, Model == Model[1])[,3]
  population_M2 = filter(r2_RF, Response == i_response, Model == Model[2])[,3]
  population_M3 = filter(r2_RF, Response == i_response, Model == Model[3])[,3]
  size_r2 = length(population_M1)
  
  bs_1 = numeric(0)
  bs_2 = numeric(0)
  for (id in 1:n_perm) {
    k_M1 = mean(sample(population_M1, 100, replace = T))
    k_M2 = mean(sample(population_M2, 100, replace = T))
    k_M3 = mean(sample(population_M3, 100, replace = T))
    bs_1 = append(bs_1, k_M2 - k_M1)
    bs_2 = append(bs_2, k_M3 - k_M2)
  }
  
  p_1 = length(which(bs_1<0))/length(bs_1)
  p_2 = length(which(bs_2<0))/length(bs_2)
  
  r2_test_all[[i_response]][["P1"]]=p_1
  r2_test_all[[i_response]][["P2"]]=p_2
 
}

```
